# Generated by Django 4.0.5 on 2023-09-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('writer', models.CharField(default='관리자', max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateField()),
            ],
        ),
    ]
