# Generated by Django 4.2.4 on 2023-09-03 00:21

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

