# Generated by Django 4.0.5 on 2023-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventNews', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(default='관리자', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='writer',
            field=models.CharField(default='관리자', max_length=200),
        ),
    ]
